name: Scam of the Week

on:
  schedule:
    - cron: '0 13 * * MON'   # runs weekly (UTC)
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'content/scam-of-the-week.json'   # notify after merge to main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: scam-of-the-week
  cancel-in-progress: true

jobs:
  generate_pr:
    name: Generate JSON & open PR
    if: github.event_name != 'push'       # run for schedule/manual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install feedparser jsonschema
          fi

      - name: Generate weekly JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # optional; script may not use it
        run: |
          python scripts/build_scam_week.py

      - name: Validate schema
        run: |
          python scripts/validate_schema.py content/scam-of-the-week.json schema/scam.schema.json

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Scam of the Week"
          title: "Weekly Scam Update"
          body: "Auto-generated update. Please review and merge."
          branch: bot/scam-update
          delete-branch: true

  notify_after_merge:
    name: Notify users (FCM)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Send FCM notification
        env:
          FCM_SERVER_KEY: ${{ secrets.FCM_SERVER_KEY }}
        run: |
          LATEST_ID=$(jq -r '.items[0].id' content/scam-of-the-week.json)
          curl -s -X POST https://fcm.googleapis.com/fcm/send \
            -H "Authorization: key=$FCM_SERVER_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"to\":\"/topics/scam_of_the_week\",\"notification\":{\"title\":\"New Scam of the Week\",\"body\":\"Tap to learn the red flags.\"},\"data\":{\"id\":\"$LATEST_ID\"}}"
